### ISSUE TITLE
MuSiC API changes broke the package

### ISSUE THREAD

**Issue by hsiaoyi0504** [eonurk/seAMLess#3]
Hi I wonder if there is anyway to get the underlying SingleCellExperiment now, given MuSiC changed their API, so current ExpressionSet could not be used anymore.

> UPDATE: Per users’ requests, we have updated MuSiC functions (version 1.0.0) and SingleCellExperiment objects are used to handle single cell references, where sparse matrices are compatible as read counts.

https://github.com/xuranw/MuSiC/commit/5e7d038e4ba679cde5d0afebf09324410575318a

**Comment by eonurk** [comment]
Yes, please use this drat option to download old version of the MuSiC as a temporary solution: 
install.packages("MuSiC", repos = "https://eonurk.github.io/drat/")

PS: sorry for the too late reply. I missed this.
